In [60]:
import glob
import os
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

In [61]:
All_games = pd.read_csv('Data/All_games.csv')
All_games.drop('Unnamed: 0', axis= 1, inplace= True)
All_games.sample(30)

,Game,Attendance,Total_goals,goals_diff,Game_Class,League
2436,Fiorentina vs Brescia,NaN,2,0,Closed_Game,IT
3226,Köln vs Hertha BSC,43600.000000,2,1,Closed_Game,BL
4303,Newcastle Utd vs West Brom,50109.666667,2,0,Closed_Game,PL
5028,Rennes vs Sochaux,NaN,2,0,Closed_Game,FL
3862,Marítimo vs Famalicão,NaN,5,2,Competitive_Open_Game,P
2211,Espanyol vs Córdoba,17128.000000,1,1,Closed_Game,SP
2800,Groningen vs VVV-Venlo,16441.000000,2,0,Closed_Game,D
171,Al-Ahli vs Al-Raed,18746.500000,4,1,Competitive_Open_Game,SPL
4552,Palermo vs Crotone,8934.000000,1,1,Closed_Game,IT
2522,Frosinone vs Fiorentina,10416.000000,1,0,Closed_Game,IT
512,Al-Ta'ee vs Al-Batin,NaN,4,2,Competitive_Open_Game,SPL
3278,Las Palmas vs Espanyol,17984.333333,2,1,Closed_Game,SP
3445,Lens vs Nantes,9123.000000,1,0,Closed_Game,FL
4380,Novara vs Juventus,NaN,4,4,One_Side_Game,IT
447,Al-Raed vs Abha,1287.500000,3,1,Competitive_Game,SPL
2848,Hamburger SV vs Augsburg,49072.250000,1,0,Closed_Game,BL
2841,Hajer vs Al-Qadsiah,106.000000,2,2,Competitive_Game,SPL
1661,Catania vs Torino,NaN,1,0,Closed_Game,IT
6201,Vitória vs Aves,13998.333333,3,2,Competitive_Game,P
426,Al-Qadsiah vs Abha,1273.000000,2,0,Closed_Game,SPL
3266,La Coruña vs Sporting Gijón,25379.000000,4,1,Competitive_Open_Game,SP
2241,Estoril vs Boavista,2379.750000,1,1,Closed_Game,P
2894,Hannover 96 vs RB Leipzig,37350.000000,4,2,Competitive_Open_Game,BL
2193,Empoli vs Palermo,7789.666667,1,1,Closed_Game,IT
348,Al-Ittihad vs Al-Ahli,35628.000000,2,1,Closed_Game,SPL
3147,Inter vs Livorno,NaN,2,2,Competitive_Game,IT
5820,Toulouse vs Nîmes,11746.000000,1,1,Closed_Game,FL
3806,Manchester Utd vs Norwich City,74295.500000,3,3,One_Side_Game,PL
3676,M'Gladbach vs Hertha BSC,49460.000000,2,1,Closed_Game,BL
2937,Hellas Verona vs Frosinone,17761.000000,3,1,Competitive_Game,IT

In [62]:
from sklearn.cluster import KMeans
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [63]:
# input games to reccomend from
# for example the games of 12 and 13 march
today = ['Brighton vs Liverpool', 'Brentford vs Burnley', 'Manchester Utd vs Tottenham',
'Hoffenheim vs Bayern Munich','Union Berlin vs Stuttgart', 'Augsburg vs Mainz 05', 'Freiburg vs Wolfsburg', 
'Levante vs Espanyol', 'Granada vs Elche', 'Villarreal vs Celta Vigo', 'Getafe vs Valencia', 'Al-Hazem vs Damac',
'AS Saint-Étienne vs Lyon']
Tomorrow = ['Leeds United vs Norwich City', 'Chelsea vs Newcastle Utd', 'West Ham vs Aston Villa',
'Southampton vs Watford','Everton vs Wolves', 'Arsenal vs Leicester City', 'Manchester City vs Leeds United', 'Barcelona vs Osasuna', 
'Real Sociedad vs Alavés', 'Betis vs Athletic Club', 'Dortmund vs Arminia', 'Leverkusen vs Köln', 'Al-Raed vs Al-Hilal',
'Al-Shabab vs Al-Ittihad', 'Paris S-G vs Bordeaux', 'Bres vs Marseille', 'Milan vs Empoli', 'Fiorentina vs Bologna', 
'Torino vs Inter', 'Lazio vs Venezia', 'Sampdoria vs Juventus', 'Hellas Verona vs Napoli', 'Udinese vs Roma']

In [64]:
All_games2 = pd.DataFrame()
def inputgame(d):
    global All_games2
    for i in range(len(d)):
        All_games2=  All_games2.append(All_games[All_games['Game'].str.contains(d[i])])
    return All_games2.reset_index(drop= True, inplace=True)

In [65]:
inputgame(Tomorrow)
All_games2

,Game,Attendance,Total_goals,goals_diff,Game_Class,League
0,Chelsea vs Newcastle Utd,41155.200000,2,2,Competitive_Game,PL
1,West Ham vs Aston Villa,34885.500000,1,0,Closed_Game,PL
2,Southampton vs Watford,29280.800000,2,1,Closed_Game,PL
3,Everton vs Wolves,27914.000000,3,1,Competitive_Game,PL
4,Arsenal vs Leicester City,59828.600000,3,1,Competitive_Game,PL
5,Manchester City vs Leeds United,52401.000000,5,4,One_Side_Game,PL
6,Barcelona vs Osasuna,63989.000000,6,5,One_Side_Game,SP
7,Real Sociedad vs Alavés,24205.000000,2,2,Competitive_Game,SP
8,Betis vs Athletic Club,40053.000000,2,1,Closed_Game,SP
9,Dortmund vs Arminia,NaN,3,3,One_Side_Game,BL
10,Leverkusen vs Köln,30210.000000,4,2,Competitive_Open_Game,BL
11,Al-Raed vs Al-Hilal,8774.000000,2,2,Competitive_Game,SPL
12,Al-Shabab vs Al-Ittihad,5896.833333,3,1,Competitive_Game,SPL
13,Paris S-G vs Bordeaux,46426.166667,3,1,Competitive_Game,FL
14,Milan vs Empoli,37236.750000,2,1,Closed_Game,IT
15,Fiorentina vs Bologna,26444.250000,1,1,Closed_Game,IT
16,Torino vs Inter,25210.333333,2,1,Closed_Game,IT
17,Sampdoria vs Juventus,24668.666667,2,1,Closed_Game,IT
18,Hellas Verona vs Napoli,18388.666667,2,2,Competitive_Game,IT
19,Udinese vs Roma,15844.857143,1,1,Closed_Game,IT

In [66]:
Attendance = All_games2['Attendance']
Attendance = pd.DataFrame(Attendance.fillna(All_games2.Attendance.mean()))
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
Attendance= pd.DataFrame(sc.fit_transform(Attendance))

In [67]:
Attendance =Attendance[0]

In [68]:
Attendance

0     0.594049
1     0.175654
2    -0.198363
3    -0.289573
4     1.840176
5     1.344512
6     2.117811
7    -0.537085
8     0.520496
9     0.000000
10   -0.136355
11   -1.566838
12   -1.758839
13    0.945795
14    0.332560
15   -0.387654
16   -0.469996
17   -0.506143
18   -0.925225
19   -1.094980
Name: 0, dtype: float64

In [69]:
Game = pd.get_dummies(All_games2['Game'])
Game_Class = pd.get_dummies(All_games2['Game_Class'])
League=pd.get_dummies(All_games2['League'])
Total_goals = All_games2['Total_goals']
goals_diff = All_games2['goals_diff']

In [70]:
All_games.columns

Index(['Game', 'Attendance', 'Total_goals', 'goals_diff', 'Game_Class',
       'League'],
      dtype='object')

In [71]:
features = pd.concat([Total_goals, goals_diff, League, Attendance,
                      Game_Class], axis=1)

In [72]:
from PIL import Image
import os
import matplotlib.pyplot as plt
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

In [73]:
cosSimilarities = cosine_similarity(features)

# store the results into a pandas dataframe

cos_similarities_df = pd.DataFrame(cosSimilarities)
cos_similarities_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.000000,0.554188,0.806172,0.878680,0.878937,0.919241,0.879912,0.841126,0.727192,0.833941,0.789431,0.710607,0.636390,0.827577,0.722332,0.575094,0.661653,0.657565,0.797093,0.456556
1,0.554188,1.000000,0.858443,0.652554,0.633082,0.535130,0.445543,0.341262,0.658540,0.385322,0.486715,0.280724,0.397873,0.506459,0.658811,0.544710,0.623626,0.620754,0.320335,0.455382
2,0.806172,0.858443,1.000000,0.873631,0.733627,0.829578,0.760697,0.717552,0.824237,0.758510,0.805401,0.673980,0.712952,0.715040,0.838746,0.754267,0.854645,0.853568,0.707350,0.697107
3,0.878680,0.652554,0.873631,1.000000,0.840980,0.842778,0.783942,0.821118,0.730714,0.771904,0.860704,0.770599,0.852220,0.859285,0.744777,0.580683,0.763946,0.763204,0.809178,0.544663
4,0.878937,0.633082,0.733627,0.840980,1.000000,0.855934,0.834710,0.636768,0.752371,0.684069,0.746986,0.441857,0.509439,0.904513,0.727742,0.411290,0.582052,0.574339,0.564635,0.221945
5,0.919241,0.535130,0.829578,0.842778,0.855934,1.000000,0.979230,0.804709,0.814406,0.935334,0.885593,0.672772,0.639671,0.843353,0.809380,0.621755,0.743186,0.738681,0.759729,0.493210
6,0.879912,0.445543,0.760697,0.783942,0.834710,0.979230,1.000000,0.829701,0.862357,0.925465,0.874532,0.644379,0.603945,0.847590,0.808205,0.608224,0.725014,0.719789,0.740406,0.463456
7,0.841126,0.341262,0.717552,0.821118,0.636768,0.804709,0.829701,1.000000,0.777014,0.836548,0.802146,0.869392,0.798029,0.737282,0.680610,0.643996,0.725401,0.725882,0.898612,0.627333
8,0.727192,0.658540,0.824237,0.730714,0.752371,0.814406,0.862357,0.777014,1.000000,0.746334,0.784725,0.544801,0.580814,0.773779,0.858530,0.691430,0.794297,0.789773,0.621133,0.557890
9,0.833941,0.385322,0.758510,0.771904,0.684069,0.935334,0.925465,0.836548,0.746334,1.000000,0.905407,0.760317,0.690671,0.747246,0.754700,0.658564,0.748914,0.747091,0.814386,0.588406
10,0.789431,0.486715,0.805401,0.860704,0.746986,0.885593,0.874532,0.802146,0.784725,0.905407,1.000000,0.737529,0.781114,0.823211,0.795570,0.633180,0.798149,0.796596,0.784319,0.574741
11,0.710607,0.280724,0.673980,0.770599,0.441857,0.672772,0.644379,0.869392,0.544801,0.760317,0.737529,1.000000,0.930340,0.593244,0.582199,0.640833,0.710332,0.714560,0.898660,0.710290
12,0.636390,0.397873,0.712952,0.852220,0.509439,0.639671,0.603945,0.798029,0.580814,0.690671,0.781114,0.930340,1.000000,0.669247,0.619233,0.591536,0.749696,0.753946,0.830219,0.668959
13,0.827577,0.506459,0.715040,0.859285,0.904513,0.843353,0.847590,0.737282,0.773779,0.747246,0.823211,0.593244,0.669247,1.000000,0.763890,0.496669,0.679370,0.674182,0.686722,0.362052
14,0.722332,0.658811,0.838746,0.744777,0.727742,0.809380,0.808205,0.680610,0.858530,0.754700,0.795570,0.582199,0.619233,0.763890,1.000000,0.896673,0.955086,0.951087,0.761706,0.762461
15,0.575094,0.544710,0.754267,0.580683,0.411290,0.621755,0.608224,0.643996,0.691430,0.658564,0.633180,0.640833,0.591536,0.496669,0.896673,1.000000,0.946629,0.946878,0.798330,0.952498
16,0.661653,0.623626,0.854645,0.763946,0.582052,0.743186,0.725014,0.725401,0.794297,0.748914,0.798149,0.710332,0.749696,0.679370,0.955086,0.946629,1.000000,0.999913,0.839733,0.900041
17,0.657565,0.620754,0.853568,0.763204,0.574339,0.738681,0.719789,0.725882,0.789773,0.747091,0.796596,0.714560,0.753946,0.674182,0.951087,0.946878,0.999913,1.000000,0.841457,0.904294
18,0.797093,0.320335,0.707350,0.809178,0.564635,0.759729,0.740406,0.898612,0.621133,0.814386,0.784319,0.898660,0.830219,0.686722,0.761706,0.798330,0.839733,0.841457,1.000000,0.800394
19,0.456556,0.455382,0.697107,0.544663,0.221945,0.493210,0.463456,0.627333,0.557890,0.588406,0.574741,0.710290,0.668959,0.362052,0.762461,0.952498,0.900041,0.904294,0.800394,1.000000

In [1]:

def retrieve_most_similar_games(given_game):

    print("-----------------------------------------------------------------------")
    print("Favorate game:", given_game)

    print("-----------------------------------------------------------------------")
    print("Recommended  games:")
    
    game_id = All_games2[All_games2['Game'] == given_game].index
    game_id = game_id[0]

    closest_game = cos_similarities_df[game_id].sort_values(ascending=False)[1:5+1].index
    closest_game_scores = cos_similarities_df[game_id].sort_values(ascending=False)[1:5+1]
    for i in range(len(closest_game)):
        print('Recommended Game:', All_games2['Game'][closest_game[i]])
    print('With a similarity score of:\n', closest_game_scores)

In [75]:
retrieve_most_similar_games('Barcelona vs Osasuna')

-----------------------------------------------------------------------
Favorate game: Barcelona vs Osasuna
-----------------------------------------------------------------------
Recommended  games:
Recommended Game: Manchester City vs Leeds United
Recommended Game: Dortmund vs Arminia
Recommended Game: Chelsea vs Newcastle Utd
Recommended Game: Leverkusen vs Köln
Recommended Game: Betis vs Athletic Club
With a similarity score of:
 5     0.979230
9     0.925465
0     0.879912
10    0.874532
8     0.862357
Name: 6, dtype: float64